Repository targeek/guru-erp, pull requests merged in 2019-04, with the labels that each got.

#95 Implement mocking dashboard ui layout
  .gitignore
  .vscode/settings.json
  packages/locales/languages/dev/main.missing.json
  packages/locales/languages/en/main.json
  packages/locales/languages/en/main.missing.json
  packages/locales/languages/vi/main.json
  packages/locales/locales.json
  packages/locales/src/builder.ts
  packages/server/src/services/mailer/__test__/mailer.units.spec.ts
  packages/web-app/.storybook/addons.ts
  packages/web-app/package.json
  packages/web-app/public/fonts/product-sans/Product Sans Bold Italic.ttf
  packages/web-app/public/fonts/product-sans/Product Sans Bold.ttf
  packages/web-app/public/fonts/product-sans/Product Sans Italic.ttf
  packages/web-app/public/fonts/product-sans/Product Sans Regular.ttf
  packages/web-app/src/App.css
  packages/web-app/src/App.tsx
  packages/web-app/src/components/RightDrawer/RightDrawer.tsx
  packages/web-app/src/components/RightDrawer/index.ts
  packages/web-app/src/components/navigations/AppBar/AppBar.tsx
  packages/web-app/src/components/navigations/AppBar/index.ts
  packages/web-app/src/components/navigations/DrawerNav/DrawerNav.story.tsx
  packages/web-app/src/components/navigations/DrawerNav/DrawerNav.tsx
  packages/web-app/src/components/navigations/DrawerNav/components/MenuListItem.tsx
  packages/web-app/src/components/navigations/DrawerNav/components/PrimaryDrawer.tsx
  packages/web-app/src/components/navigations/DrawerNav/components/SecondaryDrawer.tsx
  packages/web-app/src/components/navigations/DrawerNav/index.ts
  packages/web-app/src/constants/services.ts
  packages/web-app/src/constants/variables.ts
  packages/web-app/src/containers/Dashboard/Dashboard.tsx
  packages/web-app/src/containers/Dashboard/index.ts
  packages/web-app/src/helpers/i18next.ts
  packages/web-app/src/hooks/useRightDrawer.tsx
  packages/web-app/src/index.css
  packages/web-app/src/index.tsx
  packages/web-app/src/logo.svg
  packages/web-app/src/providers/MaterialUIProvider.tsx
  tslint.json
  yarn.lock
Labels: Waiting For Review, development, package: web

#117 chore(removate): auto assign reviewers @duongdev
  renovate.json
Labels: Waiting For Review

#135 feat(apollo.config.js): add vscode apollo plugin configuration
  apollo.config.js
Labels: In Review

#156 Add Heroku configurations for staging
  .circleci/config.yml
  Procfile
  packages/server/.env
  packages/server/.env.development
  packages/server/.gitignore
  packages/server/jest.config.js
  packages/server/package.json
  packages/server/src/moleculer.config.ts
  packages/server/src/utils/dotenv.ts
  packages/server/tsconfig.json
  packages/web-app/package.json
  packages/web-app/public/_redirects
  yarn.lock
Labels: Waiting For Review, development, enhancement

#166 feat(heroku): update build script to fasten startup environment
  Procfile
  package.json
Labels: enhancement

#194 feat(server): add git-repo-info to add api version info into response headers
  packages/locales/languages/en/accounts.missing.json
  packages/locales/languages/en/auth.missing.json
  packages/locales/languages/en/main.missing.json
  packages/locales/locales.json
  packages/server/.gitignore
  packages/server/git-repo-info.js
  packages/server/package.json
  packages/server/src/services/gateway/__test__/gateway.integrations.spec.ts
  packages/server/src/services/gateway/gateway.service.ts
  packages/server/src/services/gateway/generated-schema.gql
  packages/server/src/utils/git-repo-info.ts
  yarn.lock
Labels: Waiting For Review
